

color:

  title_input_string: "#970000"

  text_item_name: "#006E97"
  text_cool: "#F0A10C"
  text_item_controls: "#AD6DFF"
  text_item_header: "#E1E1E1"
  text_item_base: "#787878"
  text_cool_dark: "#333C4B"

  umbral_glow: "#FFFFFF"


angle:

  umbral_blade_idle_period: 0.3926991     # π/8


physics:

  thrown_items_gravity_damper: 46.0
  thrown_items_trajectory_rotation: 0.03696

  thrown_items_display_offset_x: -0.5
  thrown_items_display_offset_y: 0.1
  thrown_items_display_offset_z: 0.5

  thrown_items_origin_offset_forward: 0.5
  thrown_items_origin_offset_up: 0.1
  thrown_items_origin_offset_back: -0.25

  thrown_items_rotation_speed_sword: 0.0
  thrown_items_rotation_speed_axe: -0.3926991        # -π/8
  thrown_items_rotation_speed_hoe: -0.3926991
  thrown_items_rotation_speed_pickaxe: -0.3926991
  thrown_items_rotation_speed_shovel: -0.3926991
  thrown_items_rotation_speed_shield: -0.3926991

  thrown_items_rotation_speed_default_speed: 0.09817477  # π/32

  attack_velocity_grounded_damping_horizontal: 0.3
  attack_velocity_grounded_damping_vertical: 0.4

  attack_velocity_knockback_vertical_base: 0.25
  attack_velocity_knockback_horizontal_modifier: 0.1
  attack_velocity_knockback_normal_multiplier: 0.7


combat:

  shards_lost_percent_toughness_reset: 0.75
  toughness_recharge_percent: 0.75

  attacks_base_damage: 20.0
  attacks_down_air_threshold: -0.85

  attacks_cast_timing_min_duration: 1
  attacks_cast_timing_max_duration: 3
  attacks_cast_timing_reduction_rate: 0.2

  attacks_duration_multiplier: 500

  attacks_range_multipliers_basic_1: 1.4
  attacks_range_multipliers_basic_2: 1.4
  attacks_range_multipliers_basic_3: 1.4
  attacks_range_multipliers_neutral_air: 1.3
  attacks_range_multipliers_down_air: 1.2

  hitboxes_basic_reach: 1.5
  hitboxes_basic_width: 1.5
  hitboxes_basic_height: 1.5

  hitboxes_down_air_reach: 1.6
  hitboxes_down_air_width: 1.4
  hitboxes_down_air_height: 2.5

  hitboxes_secant_radius: 0.4

  thrown_damage_sword_damage_multiplier: 1.0
  thrown_damage_item_velocity_multiplier: 1.5
  thrown_damage_base_thrown_damage: 12.0

  thrown_damage_sword_axe_invulnerability_ticks: 0
  thrown_damage_sword_axe_base_shards: 2
  thrown_damage_sword_axe_toughness_damage: 75.0
  thrown_damage_sword_axe_soulfire_reduction: 50.0
  thrown_damage_sword_axe_knockback_grounded: 0.7
  thrown_damage_sword_axe_knockback_airborne: 1.0

  thrown_damage_other_invulnerability_ticks: 0
  thrown_damage_other_base_shards: 2
  thrown_damage_other_toughness_damage: 75.0
  thrown_damage_other_soulfire_reduction: 50.0
  thrown_damage_other_knockback_multiplier: 0.7
  thrown_damage_other_explosion_power: 1.0

  impalement_damage_per_tick: 2.0
  impalement_ticks_between_damage: 10
  impalement_max_impalements: 3
  impalement_head_zone_ratio: 0.8

  impalement_head_follow_exceptions:
    - SPIDER

  impalement_pin_max_iterations: 50
  impalement_pin_check_interval: 2

  attack_class_exempt_from_combat:
    - ARMOR_STAND
    - ITEM_FRAME
    - GLOW_ITEM_FRAME
    - PAINTING
    - ITEM_DISPLAY
    - BLOCK_DISPLAY
    - TEXT_DISPLAY
    - INTERACTION

  attack_class_timing_attack_duration: 750
  attack_class_timing_attack_iterations: 50
  attack_class_timing_attack_start_value: 0.0
  attack_class_timing_attack_end_value: 1.0

  attack_class_modifiers_range_multiplier: 1.0

  attack_class_hit_invuln_ticks: 5
  attack_class_hit_shards: 1
  attack_class_hit_toughness: 15
  attack_class_hit_soulfire: 6


timing:

  thrown_items_catch_grace_period: 3
  thrown_items_disposal_timeout: 200
  thrown_items_disposal_check_interval: 10
  thrown_items_pin_delay: 2
  thrown_items_throw_completion_delay: 6

  intervals_entity_tick: 1
  intervals_status_display_update: 5
  intervals_combat_cleanup: 20

  attacks_combo_window_base: 3


display:

  default_teleport_duration: 2

  status_display_enabled: true
  status_display_height_offset: 2.0
  status_display_update_interval: 5
  status_display_block_brightness: 15
  status_display_sky_brightness: 15

  item_display_follow_update_interval: 2
  item_display_follow_particle_interval: 4
  item_display_follow_billboard_mode: FIXED

  particles_enabled: true
  particles_density: 10


detection:

  ground_check_max_distance: 0.3

  raytrace_max_distance: 50.0
  raytrace_step_size: 0.1
  raytrace_ignore_passable_blocks: true

  throw_pin_ray_distance: 1.0
  throw_ground_check_multiplier: 0.1
  throw_hit_check_dist_multiplier: 0.6
  throw_hit_check_ray_size: 1.0

  entity_detection_search_radius: 10.0
  entity_detection_include_spectators: false


audio:

  sounds_enabled: true

  sounds_global_volume: 1.0
  sounds_global_pitch: 1.0

  throw_sound: ENTITY_ENDER_DRAGON_FLAP
  throw_volume: 0.35
  throw_pitch: 0.4

  attack_sound: ITEM_TRIDENT_THROW
  attack_volume: 0.055
  attack_pitch: 1.5

  entity_hit_connect_volume: 0.9
  entity_hit_connect_pitch: 1.0


entity:

  player_base_health: 100.0
  player_base_toughness: 100.0
  player_base_soulfire: 100.0

  hostile_health_multiplier: 1.0
  hostile_damage_multiplier: 1.0

  combat_profile_max_air_dodges: 1
  combat_profile_shards_current: 6.0
  combat_profile_shards_regen_period: 200
  combat_profile_shards_regen_amount: 1.0
  combat_profile_toughness_current: 100.0
  combat_profile_toughness_regen_period: 20
  combat_profile_toughness_regen_amount: 0.5
  combat_profile_soulfire_current: 100.0
  combat_profile_soulfire_regen_period: 5
  combat_profile_soulfire_regen_amount: 0.2
  combat_profile_form_current: 10.0
  combat_profile_form_regen_period: 60
  combat_profile_form_regen_amount: 1.0

  hit_tough_break_recharge_amount_percent: 2.0
  hit_tough_break_recharge_period_percent: 0.2
  hit_tough_break_recharge_cutoff_percent: 0.6


movement:

  dash_max_distance: 10.0
  speed_duration: 5
  speed_amplifier: 3
  dash_cast_duration: 5
  dash_base_power: 0.7
  dash_initial_offset_y: 0.3
  dash_impedance_check_offset_y: 0.5
  dash_forward_multiplier: 0.5
  dash_upward_multiplier: 0.15
  dash_upward_boost: 0.05
  dash_ray_hitbox_radius: 0.7
  dash_secant_radius: 0.3
  dash_grab_distance_squared: 8.5
  dash_block_check_offset_y: -0.75
  dash_velocity_damping: 0.6
  dash_particle_task_delay: 0
  dash_particle_task_period: 2
  dash_particle_timer_increment: 2
  dash_particle_timer_threshold: 4
  dash_grab_check_delay: 4
  dash_velocity_task_delay: 0
  dash_velocity_task_period: 1
  dash_particle_count: 100
  dash_particle_spread_x: 1.25
  dash_particle_spread_y: 1.25
  dash_particle_spread_z: 1.25
  dash_flap_sound_volume: 0.6
  dash_flap_sound_pitch: 1.0
  dash_sweep_sound_volume: 0.3
  dash_sweep_sound_pitch: 0.6

  toss_base_force: 1.5
  toss_might_multiplier_base: 2.5
  toss_might_multiplier_increment: 0.1
  toss_upward_phase_iterations: 2
  toss_upward_velocity_y: 0.25
  toss_forward_phase_iterations: 3
  toss_animation_iterations: 15
  toss_location_offset_multiplier: 0.3
  toss_particle_height_multiplier: 0.5
  toss_ray_trace_distance_multiplier: 0.6
  toss_entity_detection_radius: 0.4
  toss_knockback_multiplier: 0.3
  toss_explosion_power: 2.0
  toss_hit_invulnerability_ticks: 3
  toss_hit_shard_damage: 2
  toss_hit_toughness_damage: 30.0
  toss_hit_soulfire_reduction: 5.0

  grab_pull_strength: 0.8
  grab_max_range: 3.0
  grab_hold_duration: 40


world:

  block_interaction_allow_block_breaking: false
  block_interaction_respect_world_guard: true

  explosions_set_fire: false
  explosions_break_blocks: false


debug:

  logging_verbose_combat: false
  logging_verbose_movement: false
  logging_verbose_config: false

  visualization_show_hitboxes: false
  visualization_show_raytraces: false


grab:

  case_duration: 12
  base_duration: 60
  base_range: 3.0
  base_thickness: 0.6

  duration_scaling: 0.2
  range_scaling: 0.1
  thickness_scaling: 0.1

  hold_distance: 2.0
  hold_buffer: 0.4
  pull_speed: 0.6

  vertical_force_threshold: 1.2
  close_y_velocity_scale: 0.25

  jump_boost_amplifier: 1
  jump_boost_duration: 2

  executor_horizontal_dampening: 0.2


umbral:

  time_cutoff: 1.2
  time_scaling_factor: 9
  on_release: 3

